spring.application.name=warehouse-management-system-backend

# =============================================
# Postgres Database Configuration
# =============================================
#spring.datasource.url=jdbc:postgresql://localhost:5432/wms_db
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =============================================
# H2 Database Configuration
# =============================================
spring.datasource.url=jdbc:h2:file:./db/wms-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=

# H2 Console (for development/debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
